import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative min-h-screen antialiased">
        <div className="absolute inset-0 bg-[url('/background.png')] bg-cover bg-center z-0" />

        <div className="absolute inset-0 bg-[#DA2653]/90 z-10" />

        <div className="relative z-20">{children}</div>
      </body>
    </html>
  );
}
